modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EltrutLikes/Moogloom/issues"
[[mods]]
modId="moogloom"
version="1.0.0"
displayName="Moogloom"
logoFile="moogloom.png"
credits="Catscythe, EltrutLikes"
authors="Catscythe's Corner"
description='''

'''

[[dependencies.moogloom]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moogloom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moogloom]]
 modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

